# Generated by Django 2.1 on 2018-08-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop', '0002_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=17, null=True)),
                ('is_eagle_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
