# Generated by Django 2.1 on 2018-08-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop', '0003_meritbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('number', models.CharField(max_length=4)),
                ('revision', models.CharField(max_length=5)),
                ('short_desc', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=255)),
                ('rank', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
