# Generated by Django 2.1 on 2018-08-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troop', '0004_rankrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankrequirement',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troop.Rank'),
        ),
    ]
