# Generated by Django 2.1 on 2018-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop', '0006_auto_20180805_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankrequirement',
            name='header',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='rankrequirement',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rankrequirement',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankrequirement',
            name='short_desc',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
